# Generated by Django 5.2.17 on 2026-09-15 15:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import trainer.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('answer', models.TextField(max_length=6000, verbose_name='Пример ответа')),
                ('expected_min', models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Ожидаемый минимум')),
                ('expected_max', models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Ожидаемый максимум')),
                ('expected_hard', models.CharField(choices=[('unverified', 'Не проверялся'), ('passed', 'Сохранён'), ('violated', 'Искажён')], default='unverified', max_length=12, verbose_name='Ожидаемый hard')),
                ('scenario', models.CharField(choices=[('normal', 'Успешная тестовая оценка'), ('hard_error', 'Тест: ошибка в hard-части'), ('transient', 'Тест: временный сбой и повтор'), ('failure', 'Тест: постоянный сбой')], default='normal', max_length=12, verbose_name='Тестовый сценарий')),
            ],
            options={
                'verbose_name': 'пример калибровки',
                'verbose_name_plural': 'Калибратор — примеры',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('category', models.CharField(default='Поддержка бизнеса', max_length=80, verbose_name='Тема')),
                ('customer_message', models.TextField(max_length=4000, verbose_name='Сообщение клиента')),
                ('hard_answer', models.TextField(max_length=4000, verbose_name='Исходный hard-ответ')),
                ('required_facts', models.TextField(help_text='Один факт на строку.', verbose_name='Обязательные факты')),
                ('allowed_actions', models.TextField(blank=True, verbose_name='Допустимые следующие действия')),
                ('forbidden_promises', models.TextField(blank=True, verbose_name='Запрещённые обещания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=12, verbose_name='Статус')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('rated', 'Конкурс'), ('sandbox', 'Песочница')], default='rated', max_length=8)),
                ('snapshot', models.JSONField(default=dict)),
                ('rubric', models.JSONField(default=trainer.models.default_rubric)),
                ('status', models.CharField(choices=[('writing', 'В работе'), ('queued', 'В очереди'), ('evaluating', 'Проверяется'), ('retry', 'Повторная проверка'), ('graded', 'Проверено'), ('review', 'Нужен пересмотр')], default='writing', max_length=12, verbose_name='Статус')),
                ('answer', models.TextField(blank=True, max_length=6000, verbose_name='Ответ')),
                ('draft_revision', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(null=True)),
                ('graded_at', models.DateTimeField(null=True)),
                ('timed_out', models.BooleanField(default=False, verbose_name='Время вышло')),
                ('queue_job_id', models.BigIntegerField(null=True)),
                ('evaluation_tries', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=240, verbose_name='Ошибка')),
                ('score', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Баллы')),
                ('hard_verdict', models.CharField(choices=[('unverified', 'Не проверялся'), ('passed', 'Сохранён'), ('violated', 'Искажён')], default='unverified', max_length=12, verbose_name='Hard')),
                ('demo_scenario', models.CharField(choices=[('normal', 'Успешная тестовая оценка'), ('hard_error', 'Тест: ошибка в hard-части'), ('transient', 'Тест: временный сбой и повтор'), ('failure', 'Тест: постоянный сбой')], default='normal', max_length=12)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainer.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='Событие')),
                ('object_id', models.CharField(max_length=64, verbose_name='Объект')),
                ('details', models.JSONField(default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_min', models.PositiveSmallIntegerField()),
                ('expected_max', models.PositiveSmallIntegerField()),
                ('expected_hard', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='trainer.attempt')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.calibrationcase')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание')),
                ('daily_limit', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Заданий в день')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)], verbose_name='Секунд на задание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Идёт'), ('finished', 'Итоги зафиксированы')], default='draft', max_length=12, verbose_name='Статус')),
                ('rubric', models.JSONField(default=trainer.models.default_rubric, verbose_name='Профиль оценки')),
                ('first_prize', models.PositiveIntegerField(default=10000, verbose_name='1 место, T-Money')),
                ('second_prize', models.PositiveIntegerField(default=7000, verbose_name='2 место, T-Money')),
                ('third_prize', models.PositiveIntegerField(default=5000, verbose_name='3 место, T-Money')),
                ('final_standings', models.JSONField(default=list, editable=False, verbose_name='Зафиксированный рейтинг')),
                ('finalized_at', models.DateTimeField(editable=False, null=True)),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('exercises', models.ManyToManyField(blank=True, to='trainer.exercise', verbose_name='Задания')),
            ],
            options={
                'verbose_name': 'конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainer.contest', verbose_name='Конкурс'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.contest'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('backend', models.CharField(default='demo', max_length=40)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='trainer.attempt')),
            ],
        ),
        migrations.AddField(
            model_name='calibrationcase',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.exercise', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.exercise', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.exercise'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['contest', 'mode', 'status'], name='trainer_att_contest_f3ae7f_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', 'expires_at'], name='trainer_att_status_93e621_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__lte', 100), _connector='OR'), name='score_range'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignment__isnull', False), ('contest__isnull', False), ('mode', 'rated')), models.Q(('assignment__isnull', True), ('contest__isnull', True), ('mode', 'sandbox')), _connector='OR'), name='attempt_mode_links'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('contest', 'user', 'day', 'slot'), name='unique_daily_slot'),
        ),
    ]
