# Generated by Django 5.2.17 on 2026-09-16 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at'], 'permissions': [('review_attempt', 'Пересматривать оценки сотрудников')], 'verbose_name': 'попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.AddField(
            model_name='attempt',
            name='reviewed_skills',
            field=models.JSONField(default=dict, editable=False, verbose_name='Навыки после пересмотра'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='demo_scenario',
            field=models.CharField(choices=[('real', 'Реальная оценка нейросетью'), ('normal', 'Успешная тестовая оценка'), ('hard_error', 'Тест: ошибка в hard-части'), ('transient', 'Тест: временный сбой и повтор'), ('failure', 'Тест: постоянный сбой')], default='normal', max_length=12),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='hard_verdict',
            field=models.CharField(choices=[('unverified', 'Не проверялся'), ('passed', 'Сохранён'), ('violated', 'Искажён'), ('uncertain', 'Нужна ручная проверка')], default='unverified', max_length=12, verbose_name='Hard'),
        ),
        migrations.AlterField(
            model_name='calibrationcase',
            name='expected_hard',
            field=models.CharField(choices=[('unverified', 'Не проверялся'), ('passed', 'Сохранён'), ('violated', 'Искажён'), ('uncertain', 'Нужна ручная проверка')], default='unverified', max_length=12, verbose_name='Ожидаемый hard'),
        ),
        migrations.AlterField(
            model_name='calibrationcase',
            name='scenario',
            field=models.CharField(choices=[('real', 'Реальная оценка нейросетью'), ('normal', 'Успешная тестовая оценка'), ('hard_error', 'Тест: ошибка в hard-части'), ('transient', 'Тест: временный сбой и повтор'), ('failure', 'Тест: постоянный сбой')], default='normal', max_length=12, verbose_name='Тестовый сценарий'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=60, verbose_name='Отображаемый ник')),
                ('avatar', models.CharField(choices=[('🙂', '🙂 Улыбка'), ('🦊', '🦊 Лиса'), ('🐱', '🐱 Кот'), ('🐼', '🐼 Панда'), ('🚀', '🚀 Ракета'), ('🌿', '🌿 Лист')], default='🙂', max_length=8, verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
