# Generated by Django 5.2.17 on 2026-09-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_attempt_options_attempt_reviewed_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='first_prize',
            field=models.PositiveIntegerField(default=100, verbose_name='1 место, T-Money'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='second_prize',
            field=models.PositiveIntegerField(default=70, verbose_name='2 место, T-Money'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='third_prize',
            field=models.PositiveIntegerField(default=50, verbose_name='3 место, T-Money'),
        ),
        migrations.CreateModel(
            name='EvaluationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_number', models.PositiveSmallIntegerField(default=1, verbose_name='Попытка API')),
                ('provider', models.CharField(blank=True, max_length=40, verbose_name='Провайдер')),
                ('model', models.CharField(blank=True, max_length=160, verbose_name='Модель')),
                ('prompt_version', models.CharField(blank=True, max_length=40, verbose_name='Версия промпта')),
                ('request_payload', models.JSONField(default=dict, verbose_name='Запрос (промпт)')),
                ('response_payload', models.JSONField(default=dict, verbose_name='Ответ провайдера')),
                ('normalized_payload', models.JSONField(default=dict, verbose_name='Нормализованный разбор')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('retry', 'Повторится'), ('failed', 'Ошибка'), ('review', 'На пересмотре')], max_length=12, verbose_name='Статус')),
                ('error_type', models.CharField(blank=True, max_length=80, verbose_name='Тип ошибки')),
                ('error_message', models.CharField(blank=True, max_length=240, verbose_name='Безопасное сообщение')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Время, мс')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Входные токены')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выходные токены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_traces', to='trainer.attempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'диагностика оценщика',
                'verbose_name_plural': 'Диагностика оценщика',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attempt', 'created_at'], name='trainer_eva_attempt_f7775c_idx'), models.Index(fields=['status', 'created_at'], name='trainer_eva_status_94073e_idx')],
            },
        ),
    ]
