# Generated by Django 5.2.17 on 2026-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_contest_first_prize_alter_contest_second_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtrace',
            name='error_metadata',
            field=models.JSONField(default=dict, verbose_name='Технические детали ошибки'),
        ),
    ]
