# Generated by Django 5.2.17 on 2026-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_evaluationtrace_error_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='closed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Приём завершён досрочно'),
        ),
        migrations.AlterField(
            model_name='evaluationtrace',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('retry', 'Сбой · назначен повтор'), ('failed', 'Ошибка'), ('review', 'На пересмотре')], max_length=12, verbose_name='Статус'),
        ),
    ]
