# Generated by Django 5.2.17 on 2026-09-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_contest_closed_at_alter_evaluationtrace_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='openrouter', max_length=20)),
                ('model', models.CharField(max_length=200)),
                ('openai_secret', models.TextField(blank=True)),
                ('openrouter_secret', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
