# Generated by Django 5.2.17 on 2026-09-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_aiconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationcase',
            options={'verbose_name': 'пример калибровки', 'verbose_name_plural': 'Эталонные ответы'},
        ),
        migrations.AlterModelOptions(
            name='calibrationrun',
            options={'verbose_name': 'проверка эталона', 'verbose_name_plural': 'Проверки эталонов'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'результат проверки', 'verbose_name_plural': 'Результаты проверки'},
        ),
    ]
