# Generated by Django 5.2.17 on 2026-09-23 16:29

import trainer.evaluation_prompt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_evaluationprompt_version_and_soft_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationprompt',
            name='text',
            field=models.TextField(default=trainer.evaluation_prompt.default_evaluation_prompt, max_length=20000, verbose_name='Текст промпта'),
        ),
    ]
