# Generated by Django 5.2.17 on 2026-09-23 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_roles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("trainer", "UserProfile")
    alias = schema_editor.connection.alias
    for user in User.objects.using(alias).filter(is_staff=True, is_superuser=False).iterator():
        Profile.objects.using(alias).update_or_create(user_id=user.pk, defaults={"role": "group_leader"})


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_alter_evaluationprompt_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('group_leader', 'Руководитель группы'), ('sector_leader', 'Руководитель сектора')], default='employee', max_length=20, verbose_name='Роль'),
        ),
        migrations.RunPython(preserve_existing_roles, migrations.RunPython.noop),
    ]
