# Generated by Django 5.2.17 on 2026-10-01 08:41

import dialogues.prompts
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialoguePrompt',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('client_text', models.TextField(default=dialogues.prompts.client_default, max_length=16000, verbose_name='Промпт клиента')),
                ('evaluator_text', models.TextField(default=dialogues.prompts.evaluator_default, max_length=20000, verbose_name='Промпт оценщика диалогов')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='Версия')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'промпты диалогов',
                'verbose_name_plural': 'Промпты диалогов',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('situation', models.TextField(max_length=6000, verbose_name='Ситуация и неизменные факты')),
                ('goal', models.TextField(max_length=1500, verbose_name='Цель клиента')),
                ('persona', models.TextField(max_length=1500, verbose_name='Характер и начальное настроение')),
                ('first_message', models.TextField(max_length=1500, verbose_name='Первое сообщение клиента')),
                ('first_topic', models.SlugField(default='start', max_length=40, verbose_name='Код первой темы')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)], verbose_name='Секунд на каждый ответ')),
                ('max_turns', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='Максимум ответов')),
                ('enabled', models.BooleanField(default=True, verbose_name='Доступен для тестирования')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'сценарий диалога',
                'verbose_name_plural': 'Сценарии диалогов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('prompts', models.JSONField(default=dict)),
                ('profile', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ready', 'Готов следующий ход'), ('writing', 'Ожидает ответа'), ('generating', 'Клиент печатает'), ('evaluating', 'Идёт итоговая оценка'), ('completed', 'Завершён'), ('failed', 'Нужен повтор запроса')], default='ready', max_length=16, verbose_name='Статус')),
                ('auto_advance', models.BooleanField(default=True)),
                ('closing_message', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField(null=True, verbose_name='Баллы')),
                ('operation', models.UUIDField(default=uuid.uuid4)),
                ('processing_token', models.UUIDField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('job_tries', models.PositiveSmallIntegerField(default=0)),
                ('failed_stage', models.CharField(blank=True, max_length=16)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dialogues.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'прохождение диалога',
                'verbose_name_plural': 'История диалогов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogueTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('client', 'Клиент'), ('evaluation', 'Оценщик')], max_length=16, verbose_name='Этап')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=200)),
                ('prompt_version', models.PositiveIntegerField()),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='dialogues.session')),
            ],
            options={
                'verbose_name': 'запрос диалога',
                'verbose_name_plural': 'Запросы диалогов к нейросети',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='Код темы')),
                ('title', models.CharField(max_length=120, verbose_name='Тема вопроса')),
                ('hard_answer', models.TextField(max_length=4000, verbose_name='Правильный hard-ответ')),
                ('required_facts', models.TextField(help_text='По одному на строку. При оценке учитывается уже сказанное в диалоге.', max_length=3000, verbose_name='Обязательные факты')),
                ('allowed_next', models.CharField(blank=True, help_text='Коды через запятую. Пусто — любая тема сценария. Текущую тему можно уточнять всегда.', max_length=400, verbose_name='Следующие темы')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dialogues.scenario')),
            ],
            options={
                'verbose_name': 'hard-блок диалога',
                'verbose_name_plural': 'Hard-блоки диалога',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'code'), name='dialogue_topic_code')],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('topic_code', models.CharField(max_length=40)),
                ('client_message', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=80)),
                ('answer', models.TextField(blank=True, max_length=6000)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('timed_out', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='dialogues.session')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'number'), name='dialogue_turn_number')],
            },
        ),
    ]
